In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/bigdata/커리어넷_직업백과.csv')

In [ ]:
key = '29c85897053f2d7e2ea35c3820b18086'
start = 1
last = 61

url = f"https://www.career.go.kr/cnet/front/openapi/jobs.json?apiKey={key}"
params = {"pageSize": 10, "pageIndex": 1}
r = requests.get(url, params = params)

data = r.json()
data

{'count': 546,
 'pageSize': 10,
 'pageIndex': 1,
 'jobs': [{'aptit_name': '안전 관련직',
   'social': '보통미만',
   'work': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.',
   'job_cd': 1,
   'rel_job_nm': '가스검침원, 전기검침원, 수도계량원, 검침원',
   'job_nm': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
   'top_nm': '미용·여행·숙박·음식·경비·청소직',
   'wlb': '매우좋음',
   'RNUM': 1.0,
   'edit_dt': 1757495137000,
   'reg_dt': 1677056400000,
   'seq': 2,
   'views': 81063,
   'likes': 18,
   'wage': '3천만원↓'},
  {'aptit_name': '이학 전문직',
   'social': '매우좋음',
   'work': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.',
   'job_cd': 5,
   'rel_job_nm': '기상관측요원',
   'job_nm': '일기예보관',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '좋음',
   'RNUM': 2.0,
   'edit_dt': 1683617807000,
   'reg_dt': 1677056400000,
   'seq': 5,
   'views': 91812,
   'likes': 32,
   'wage': '4천만원↑'},
  {'aptit_name': '이학 전문직',
   'social': '매우좋음',
   'work': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.',
   'job_cd': 6,
   'rel_job_nm': '기상학연구원',
   'job_nm': '기상연구원',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '좋음',
   'RNUM': 3.0,
   'edit_dt': 1749029209000,
   'reg_dt': 1677056400000,
   'seq': 8,
   'views': 188811,
   'likes': 90,
   'wage': '4천만원↑'},
  {'aptit_name': '이학 전문직',
   'social': '매우좋음',
   'work': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.',
   'job_cd': 8,
   'rel_job_nm': '광물리학자, 물리학자, 핵물리학자',
   'job_nm': '물리학연구원',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '좋음',
   'RNUM': 4.0,
   'edit_dt': 1677056400000,
   'reg_dt': 1677056400000,
   'seq': 11,
   'views': 267284,
   'likes': 298,
   'wage': '5천만원↑'},
  {'aptit_name': '의료관련 전문직',
   'social': '좋음',
   'work': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.',
   'job_cd': 10,
   'rel_job_nm': '진단방사선사',
   'job_nm': '방사선사',
   'top_nm': '보건·의료직',
   'wlb': '매우좋음',
   'RNUM': 5.0,
   'edit_dt': 1757491974000,
   'reg_dt': 1677056400000,
   'seq': 14,
   'views': 245608,
   'likes': 80,
   'wage': '3천만원↑'},
  {'aptit_name': '이학 전문직',
   'social': '매우좋음',
   'work': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.',
   'job_cd': 13,
   'rel_job_nm': '생태학자, 유전학자, 생물학자',
   'job_nm': '생물학연구원',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '좋음',
   'RNUM': 6.0,
   'edit_dt': 1677056400000,
   'reg_dt': 1677056400000,
   'seq': 17,
   'views': 434300,
   'likes': 366,
   'wage': '4천만원↑'},
  {'aptit_name': '의료관련 전문직',
   'social': '매우좋음',
   'work': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.',
   'job_cd': 15,
   'rel_job_nm': '수의테크니션',
   'job_nm': '수의사',
   'top_nm': '보건·의료직',
   'wlb': '매우좋음',
   'RNUM': 7.0,
   'edit_dt': 1757495155000,
   'reg_dt': 1677056400000,
   'seq': 20,
   'views': 739982,
   'likes': 1407,
   'wage': '5천만원↑'},
  {'aptit_name': '이학 전문직',
   'social': '매우좋음',
   'work': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.',
   'job_cd': 17,
   'rel_job_nm': '순수수학자, 응용수학자, 수학자',
   'job_nm': '수학연구원',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '좋음',
   'RNUM': 8.0,
   'edit_dt': 1677056400000,
   'reg_dt': 1677056400000,
   'seq': 23,
   'views': 221727,
   'likes': 216,
   'wage': '5천만원↑'},
  {'aptit_name': '기능직',
   'social': '매우좋음',
   'work': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.',
   'job_cd': 19,
   'rel_job_nm': '심전도기사',
   'job_nm': '의료장비기사',
   'top_nm': '설치·정비·생산직',
   'wlb': '좋음',
   'RNUM': 9.0,
   'edit_dt': 1677056400000,
   'reg_dt': 1677056400000,
   'seq': 26,
   'views': 59986,
   'likes': 24},
  {'aptit_name': '인문 및 사회과학 관련직',
   'social': '좋음',
   'work': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.',
   'job_cd': 20,
   'rel_job_nm': '교육심리학자, 발달심리학자, 사회심리학자, 산업심리학자, 상담심리학자',
   'job_nm': '심리학연구원',
   'top_nm': '연구직 및 공학 기술직',
   'wlb': '매우좋음',
   'RNUM': 10.0,
   'edit_dt': 1677056400000,
   'reg_dt': 1677056400000,
   'seq': 29,
   'views': 482744,
   'likes': 357,
   'wage': '5천만원↑'}]}

In [ ]:
count = data.get("count")

if count:
  total_pages = (count + params["pageSize"]-1) // params['pageSize']

In [ ]:
jobs = data.get("jobs", [])

all_jobs = jobs[:]
current_page = params["pageIndex"]

for p in range(current_page+1, total_pages+1):
  params["pageIndex"] = p
  page_data = r.json()
  page_jobs = page_data.get("jobs",[])
  if not page_jobs:
    break
  all_jobs.extend(page_jobs)

print("총 직업: ", len(all_jobs))

총 직업:  550

In [ ]:
information_ls = []

for i in all_jobs:
  information_dict = {}
  information_dict["직업명"] = i["job_nm"]
  information_dict["직업코드"] = i["seq"]
  information_dict["업무"] = i["work"]
  information_ls.append(information_dict)

information_ls

[{'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',
  '직업코드': 29,
  '업무': '심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학, 교육, 산업 현장에 적용할 수 있는 심리학적 지식과 정보를 제공합니다.'},
 {'직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업코드': 2,
  '업무': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
 {'직업명': '일기예보관',
  '직업코드': 5,
  '업무': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
 {'직업명': '기상연구원',
  '직업코드': 8,
  '업무': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
 {'직업명': '물리학연구원',
  '직업코드': 11,
  '업무': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
 {'직업명': '방사선사',
  '직업코드': 14,
  '업무': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
 {'직업명': '생물학연구원',
  '직업코드': 17,
  '업무': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
 {'직업명': '수의사',
  '직업코드': 20,
  '업무': '수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방, 진단, 처방, 치료하고 자문하며 연구하는 업무를 수행합니다.'},
 {'직업명': '수학연구원',
  '직업코드': 23,
  '업무': '수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경제학, 과학, 공학 등의 문제를 해결하기 위한 연구를 수행합니다.'},
 {'직업명': '의료장비기사',
  '직업코드': 26,
  '업무': '의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하고 개발하는 업무를 수행합니다.'},
 {'직업명': '심리학연구원',

In [ ]:
table = pd.DataFrame.from_dict(information_ls, orient = "columns")
table

,직업명,직업코드,업무
0,가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원,2,가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서...
1,일기예보관,5,일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의...
2,기상연구원,8,기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을...
3,물리학연구원,11,"물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적..."
4,방사선사,14,"방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 ..."
...,...,...,...
545,생물학연구원,17,"생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고,..."
546,수의사,20,"수의사는 개, 고양이, 소, 돼지, 물고기, 어패류 등 동물의 질병과 상해를 예방,..."
547,수학연구원,23,"수학연구원은 수학적 지식과 이론에 대해 연구하며, 수학적 이론과 기법을 활용하여 경..."
548,의료장비기사,26,의료장비기사는 병원에서 사용되는 의료 장비의 성능을 개선하거나 새로운 장비를 연구하...
549,심리학연구원,29,"심리학연구원은 인간의 행동과 정신적 과정을 과학적으로 연구하고, 연구 결과를 의학,..."

In [ ]:
path = "/content/커리어넷_직업백과.csv"
table.to_csv(path, index = False, encoding = "utf-8-sig")

In [ ]:
jobcode = df['직업코드'].tolist()
jobcode

[1,
 5,
 6,
 8,
 10,
 13,
 15,
 17,
 19,
 20,
 21,
 23,
 24,
 25,
 29,
 30,
 31,
 32,
 33,
 34,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 46,
 47,
 48,
 49,
 50,
 52,
 53,
 54,
 56,
 57,
 58,
 59,
 61,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 73,
 74,
 75,
 76,
 77,
 81,
 83,
 84,
 85,
 86,
 87,
 88,
 90,
 92,
 97,
 98,
 100,
 101,
 102,
 104,
 106,
 107,
 108,
 109,
 110,
 112,
 113,
 114,
 119,
 120,
 121,
 122,
 125,
 126,
 127,
 129,
 131,
 132,
 133,
 137,
 138,
 139,
 140,
 142,
 143,
 144,
 145,
 147,
 148,
 149,
 150,
 151,
 153,
 155,
 157,
 159,
 162,
 163,
 164,
 165,
 166,
 167,
 169,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 182,
 183,
 186,
 187,
 189,
 190,
 192,
 193,
 195,
 198,
 199,
 201,
 202,
 203,
 205,
 206,
 207,
 208,
 209,
 211,
 212,
 214,
 215,
 217,
 219,
 222,
 223,
 224,
 226,
 230,
 231,
 232,
 233,
 234,
 236,
 238,
 239,
 240,
 242,
 243,
 244,
 247,
 252,
 253,
 255,
 256,
 258,
 260,
 261,
 262,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 278,
 280,
 281,
 283,
 284,
 285,
 286,
 288,
 291,
 293,
 294,
 295,
 296,
 298,
 299,
 301,
 303,
 304,
 305,
 306,
 309,
 310,
 311,
 313,
 314,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 325,
 326,
 327,
 328,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 344,
 345,
 346,
 347,
 348,
 349,
 352,
 353,
 354,
 355,
 356,
 358,
 359,
 360,
 362,
 363,
 364,
 365,
 366,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 378,
 379,
 380,
 383,
 384,
 385,
 386,
 388,
 390,
 391,
 392,
 395,
 396,
 397,
 398,
 400,
 401,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 426,
 427,
 428,
 429,
 430,
 431,
 435,
 440,
 441,
 443,
 444,
 450,
 452,
 457,
 458,
 459,
 462,
 465,
 466,
 467,
 469,
 470,
 474,
 475,
 476,
 481,
 539,
 592,
 626,
 740,
 795,
 834,
 911,
 914,
 915,
 916,
 917,
 920,
 922,
 923,
 926,
 927,
 928,
 929,
 933,
 934,
 937,
 938,
 941,
 946,
 948,
 950,
 951,
 952,
 954,
 957,
 963,
 966,
 968,
 973,
 975,
 976,
 978,
 985,
 988,
 994,
 995,
 997,
 1004,
 1006,
 1007,
 1009,
 1010,
 1061,
 1068,
 1076,
 1078,
 1080,
 1081,
 1087,
 1088,
 1089,
 1090,
 1092,
 1093,
 1096,
 1097,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1255,
 1256,
 1257,
 1259,
 1276,
 1277,
 1278,
 1279,
 1281,
 1282,
 1431,
 1432,
 1433,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1541,
 10001,
 10002,
 10003,
 10004,
 10005,
 10006,
 10007,
 10008,
 10009,
 10010,
 10011,
 10012,
 10013,
 10014,
 10015,
 10016,
 10017,
 10018,
 10019,
 10020,
 10021,
 10022,
 10023,
 10024,
 10025,
 10026,
 10027,
 10028,
 10029,
 10030,
 10031,
 10032,
 10033,
 10034,
 10035,
 10036,
 10037,
 10038,
 10039,
 10040,
 10041,
 10042,
 10043,
 10044,
 10045,
 10046,
 10047,
 10048,
 10049,
 10050,
 10051,
 10052,
 10053,
 10054,
 10055,
 10056,
 10057,
 10058,
 10059,
 10060,
 10061,
 10062,
 10063,
 10064,
 10065,
 10066,
 10067,
 10068,
 10069,
 10070,
 10071,
 10072,
 10073,
 10074,
 10075,
 10076,
 10077,
 10078,
 10079,
 10080,
 10101,
 10102,
 10103,
 10104,
 10105,
 10106,
 10107,
 10108,
 10109,
 10110,
 10111,
 10112]

In [ ]:
all_details = []

for code in jobcode:
  url_details = f'https://www.career.go.kr/cnet/front/openapi/job.json?apiKey={key}&seq={code}'
  r2 = requests.get(url_details)
  detail = r2.json()
  all_details.append(detail)

all_details

[{'workList': [{'work': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
   {'work': '가스, 수도, 전력 등의 사용량에 따라 검침 서류를 대단위, 소단위 소비자와 지역으로 구분하여 전산에 입력합니다.'},
   {'work': '계량기의 불량 상태 등을 점검하고, 계량기 표면의 이물질을 제거합니다.'}],
  'interestList': [{'interest': '기계나 기구를 조작하는 것을 좋아하고, 직접 느끼고 움직이는 체험을 중시하는 사람에게 적합합니다.'},
   {'interest': '고객에 대한 서비스 정신에 관심이 많고, 맡은 일에 대한 책임감이 있는 사람에게 적합합니다.'}],
  'researchList': [{'research': '에너지 진로체험 프로그램 참여 - 에너지공사에서 주관하는 에너지 관련 진로체험 프로그램에 참여하여 에너지 관련 직업의 정보에 대해 탐색해볼 수 있습니다.'},
   {'research': '에너지 키트 조립 - 에너지 실험키트, 전기키트를 통해 각종 장치의 작동원리에 대해 이해 할 수 있습니다.'}],
  'baseInfo': {'aptit_name': '안전 관련직',
   'INTRST_JOB_YN': 'N',
   'emp_job_nm': '계기 검침원 및 가스 점검원',
   'social': '보통미만',
   'emp_job_cd': '5641',
   'job_cd': 1,
   'satisfication': 63.3,
   'rel_job_nm': '가스검침원, 전기검침원, 수도계량원, 검침원',
   'job_nm': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
   'std_job_nm': '계기 검침원 및 가스 점검원',
   'wlb': '매우좋음',
   'std_job_cd': '9921',
   'wage_source': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원의 관련 직업인 계기검침원및가스점검원의 평균연봉(중앙값)은 2,799만원으로, 조사 대상 전체 직업 평균연봉(중앙값)인 4,072만원과 비교하여 낮은 수준입니다. (자료 : 워크넷, 계기검침원및가스점검원(2021))',
   'edit_dt': '2025-09-10',
   'reg_dt': '2023-02-22',
   'satisfi_source': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원의 관련 직업인 계기검침원및가스점검원의 일자리 증가 가능성, 발전가능성 및 고용안정에 대해 재직자가 느끼는 직업만족도는 63.3%입니다. (자료: 워크넷, 계기검침원및가스점검원(2021))',
   'seq': 2,
   'views': 81063,
   'likes': 18,
   'wage': '2,799'},
  'jobReadyList': {'recruit': [],
   'certificate': [],
   'training': [],
   'curriculum': [{'curriculum': '고등학교 졸업 이상의 학력이 필요합니다.'}]},
  'forecastList': [],
  'eduChart': [{'chart_name': '중졸이하,고졸,전문대졸,대졸,대학원졸,박사졸',
    'chart_data': '0,77,23,0,0,0',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'}],
  'performList': {'environment': [{'environment': '걷거나 뛰기',
     'inform': '걷거나 뛰면서 근무하는 빈도',
     'importance': 100,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '균형을 유지하기',
     'inform': '(몸의) 균형을 유지하면서 근무하는 빈도',
     'importance': 99,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '비좁은 업무 공간',
     'inform': '불편한 자세를 취해야 하는 비좁은 공간에 노출되는 빈도',
     'importance': 98,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '실외 근무',
     'inform': '바깥공기에 노출되는 실외에서 근무하는 빈도',
     'importance': 97,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '매우 춥거나 더운 기온',
     'inform': '매우 덥거나(섭씨 32도 이상) 매우 추운(섭씨 0도 이하) 기온에 노출되는 빈도',
     'importance': 93,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '불쾌하거나 무례한 사람 상대',
     'inform': '불쾌하거나, 화나거나, 혹은 무례한 사람을 대하는 빈도',
     'importance': 92,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '몸을 구부리거나 비틀기',
     'inform': '몸을 구부리거나 비틀면서 근무하는 빈도',
     'importance': 88,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '갈등 상황',
     'inform': '업무 수행 시 갈등 상황 노출 정도',
     'importance': 87,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '사물, 도구, 조종 장치를 다루기 위해 손사용',
     'inform': '손으로 사물, 도구 혹은 조종 장치를 다루면서 근무하는 빈도',
     'importance': 79,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'environment': '반복적인 신체행동, 정신적 활동',
     'inform': '지속적이고 반복적인 신체적 행동이나 정신적 활동의 중요성',
     'importance': 72,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'}],
   'perform': [{'inform': '기계가 제대로 작동하는지 확인하기 위해 표시판이나 계기판 등을 살펴본다',
     'importance': 72,
     'perform': '작동 점검',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '오작동의 원인이 무엇인가를 확인하고 이를 어떻게 처리할 것인지 결정한다',
     'importance': 54,
     'perform': '고장의 발견·수리',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '장비 혹은 시스템을 조작하고 통제한다',
     'importance': 47,
     'perform': '조작 및 통제',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '자신의 시간과 다른 사람의 시간을 관리한다',
     'importance': 35,
     'perform': '시간 관리',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
     'importance': 33,
     'perform': '수리력',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '다른 사람들을 돕기 위해 적극적으로 노력한다',
     'importance': 30,
     'perform': '서비스 지향',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '품질 또는 성과를 평가하기 위하여 제품, 서비스, 공정을 검사하거나 조사한다',
     'importance': 29,
     'perform': '품질관리분석',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '업무를 수행하는데 필요한 도구나 장비를 결정한다',
     'importance': 29,
     'perform': '장비 선정',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
     'importance': 29,
     'perform': '문제 해결',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
    {'inform': '신체의 균형을 유지하거나 각 부위를 구부리고 편다',
     'importance': 28,
     'perform': '유연성 및 균형',
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'}],
   'knowledge': [{'inform': '고객에게 서비스를 제공하는데 필요한 지식(고객의 욕구평가, 고객의 만족도 평가, 서비스 기준 설정 등)',
     'importance': 68,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '고객서비스'},
    {'inform': '집, 빌딩, 혹은 도로를 만들고 수리하기 위해 필요한 지식',
     'importance': 66,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '건축 및 설계'},
    {'inform': '기계와 도구를 사용하고, 수리·유지하는 것과 관련된 지식',
     'importance': 65,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '기계'},
    {'inform': '연산, 대수학, 통계, 기하학의 계산 및 응용에 관한 지식',
     'importance': 65,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '산수와 수학'},
    {'inform': '법률, 규정에 관한 지식',
     'importance': 63,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '법'},
    {'inform': '전화기, 네트워크, 방송 등의 통신기기를 조작하고 통제하는데 필요한 지식',
     'importance': 61,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '통신'},
    {'inform': '육지, 바다 그리고 하늘의 특성 및 상호관계에 관한 지식',
     'importance': 59,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '지리'},
    {'inform': '사람들과 재산을 보호하기 위해 필요한 지식',
     'importance': 59,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '안전과 보안'},
    {'inform': '컴퓨터의 하드웨어, 회로판, 처리장치, 반도체, 전자장비에 관한 지식',
     'importance': 56,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '컴퓨터와 전자공학'},
    {'inform': '공기, 물, 빛, 열, 전기이론 및 자연현상에 관한 지식',
     'importance': 56,
     'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]',
     'knowledge': '물리'}]},
  'majorChart': [],
  'abilityList': [{'SORT_ORDR': '01', 'ability_name': '신체·운동능력'}],
  'departList': [],
  'relSolList': [],
  'tagList': [''],
  'certiList': [],
  'relVideoList': [],
  'aptitudeList': [{'aptitude': '많은 가정을 돌아다니면서 검침 업무를 수행해야 하므로 원활한 의사소통을 하기 위한 대인관계능력이 필요합니다.'}],
  'jobRelOrgList': [{'rel_org': '한국가스공사',
    'rel_org_url': 'http://www.kogas.or.kr'},
   {'rel_org': '한국도시가스협회', 'rel_org_url': 'http://www.citygas.or.kr'},
   {'rel_org': '한국전력공사', 'rel_org_url': 'http://www.kepco.co.kr'}],
  'relJinsolList': [],
  'indicatorChart': [{'indicator': '융합성,대인관계,창의성,일가정균형,소득수준,고용유지,사회공헌',
    'indicator_data': '3.4,16.2,3.4,89.5,3.7,23.9,14.2'}]},
 {'workList': [{'work': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
   {'work': '기류의 방향, 속도, 온도, 습도, 기압 등 지구 대기의 물리적 특성과 그 특성에 영향을 미치는 요인을 조사하여 일기도를 작성합니다.'},
   {'work': '기상 관측 자료의 분석을 통해 장기, 단기 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표합니다.'}],
  'interestList': [{'interest': '기상학, 수학, 물리학에 관심이 있고, 새로운 것에 대한 호기심을 가진 사람에게 적합합니다.'},
   {'interest': '기상 관측 자료를 분석하는 것에 관심이 있고, 세심하고 꼼꼼한 성격의 사람에게 적합합니다.'}],
  'researchList': [{'research': '기후변화체험관 방문 - 기후변화체험관에 방문하여 세계의 기후변화와 환경문제에 대한 전시를 관람해볼 수 있습니다.'},
   {'research': '환경보호 공모전 참여 - 환경보호를 주제로 한 다양한 포스터, 사진 공모전 등이 개최됩니다. 대기환경을 주제로 하여 공모전에 참여해보고 환경보호의 중요성을 상기할 수 있습니다.'}],
  'baseInfo': {'aptit_name': '이학 전문직',
   'INTRST_JOB_YN': 'N',
   'emp_job_nm': '자연과학 연구원',
   'social': '매우좋음',
   'emp_job_cd': '1211',
   'job_cd': 5,
   'satisfication': 70.9,
   'rel_job_nm': '기상관측요원',
   'job_nm': '일기예보관',
   'std_job_nm': '자연과학 연구원',
   'wlb': '좋음',
   'std_job_cd': '2112',
   'wage_source': '일기예보관의 관련 직업인 천문·기상학연구원의 평균연봉(중앙값)은 4,662만원으로, 조사 대상 전체 직업 평균연봉(중앙값)인 4,072만원과 비교하여 높은 수준입니다. (자료 : 워크넷, 천문·기상학연구원(2021))',
   'edit_dt': '2023-05-09',
   'reg_dt': '2023-02-22',
   'satisfi_source': '일기예보관의 관련 직업인 천문·기상학연구원의 일자리 증가 가능성, 발전가능성 및 고용안정에 대해 재직자가 느끼는 직업만족도는 70.9%입니다. (자료: 워크넷, 천문·기상학연구원(2021))',
   'tag': '일기예보, 기상현상',
   'seq': 5,
   'views': 91812,
   'likes': 32,
   'wage': '4,662'},
  'jobReadyList': {'recruit': [{'recruit': '공개 채용이나 특별채용을 통해 기상청, 기상연구소 등의 연구 기관이나 방송국의 일기예보 담당 부서 등에 취업할 수 있습니다.'}],
   'certificate': [{'certificate': '특별히 요구되는 국가자격증이나 민간자격증은 없습니다. 다만, 국가자격증으로는 한국산업인력공단에서 시행하는 기상예보기술사, 기상기사, 기상감정기사 자격증이 있습니다.'}],
   'training': [{'training': '기상청 부설 기상 연수원에서 기상 업무와 관련된 교육과 훈련을 제공하고 있습니다.'}],
   'curriculum': [{'curriculum': '대학교에서 대기과학과, 천문학과 등 기상학이나 천문학 관련 학과를 졸업하면 유리합니다.'}]},
  'forecastList': [{'forecast': '향후 5년간 일기예보관의 관련 직업인 천문·기상학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 기초과학 분야의 연구 사업은 정부의 정책적 지원에 큰 영향을 받는데, 특히 정부가 국가경쟁력의 핵심 요소가 되는 과학기술 인력의 체계적 육성과 지원을 중요한 정책적 과제로 삼고 있고, 이에 수반되는 예산을 대폭 늘릴 예정이므로 향후 자연과학 관련 인력의 수요가 증가할 것으로 판단됩니다. 따라서 향후 천문 및 기상학연구원의 일자리도 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  'eduChart': [{'chart_name': '중졸이하,고졸,전문대졸,대졸,대학원졸,박사졸',
    'chart_data': '0,0,0,23,50,27',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
  'performList': {'environment': [],
   'perform': [{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
     'importance': 99,
     'perform': '문제 해결',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '다양한 목적을 위해 소프트웨어나 인터넷을 활용하거나 프로그램을 작성한다',
     'importance': 98,
     'perform': '전산',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '자신의 위치를 파악하거나 다른 대상들이 자신을 중심으로 어디에 있는지 안다',
     'importance': 98,
     'perform': '공간지각력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
     'importance': 96,
     'perform': '수리력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '먼 곳이나 가까운 것을 보기 위해 눈을 사용한다',
     'importance': 96,
     'perform': '시력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
     'importance': 95,
     'perform': '범주화',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '새로운 것을 배우거나 가르칠 때 적절한 방법을 활용한다',
     'importance': 95,
     'perform': '학습전략',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '문제를 해결하기 위해(혹은 의사결정을 하기 위해) 체계적으로 이치에 맞는 생각을 해낸다',
     'importance': 94,
     'perform': '논리적 분석',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '이득과 손실을 평가해서 결정을 내린다',
     'importance': 93,
     'perform': '판단과 의사결정',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '문제해결 및 의사결정을 위해 새로운 정보가 가지는 의미를 파악한다',
     'importance': 93,
     'perform': '추리력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
   'knowledge': []},
  'majorChart': [{'major': '인문계열,사회계열,교육계열,공학계열,자연계열,의학계열,예체능계열',
    'major_data': '0,0,0,27,73,0,0',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
  'abilityList': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  'departList': [{'depart_id': 111, 'depart_name': '대기과학과'},
   {'depart_id': 541, 'depart_name': '천문학과'}],
  'relSolList': [],
  'tagList': ['일기예보', ' 기상현상'],
  'certiList': [{'certi': '기상예보기술사',
    'link': 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&jmCd=0891'},
   {'certi': '기상기사',
    'link': 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&jmCd=1600'},
   {'certi': '기상감정기사',
    'link': 'https://www.q-net.or.kr/crf005.do?id=crf00505&gSite=Q&jmCd=1601'}],
  'relVideoList': [],
  'aptitudeList': [{'aptitude': '기상 관측 자료의 분석을 바탕으로 일기예보를 하기 위해서 논리적으로 사고하여 문제를 해결할 수 있는 수리·논리력이 필요합니다.'}],
  'jobRelOrgList': [{'rel_org': '기상청 날씨누리',
    'rel_org_url': 'https://www.weather.go.kr'},
   {'rel_org': '국립기상과학원', 'rel_org_url': 'http://www.nims.go.kr'}],
  'relJinsolList': [],
  'indicatorChart': [{'indicator': '융합성,대인관계,창의성,일가정균형,소득수준,고용유지,사회공헌',
    'indicator_data': '97.2,43.1,87.7,65.5,86.5,76.8,92.2',
    'source': '[자료 : 한국직업능력연구원, 맞춤형취업지원을 위한 직업지표 연구(2020-22)]'}]},
 {'workList': [{'work': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
   {'work': '기류의 방향, 속도, 기압, 온도, 습도 등 기상현상과 대기, 기후, 해양기상, 지진 특성 등을 조사하고 분석하여 보다 정확한 일기예보 기법을 개발하기 위한 연구를 합니다.'},
   {'work': '대기 상황에 대한 자료를 분석하고, 장기, 단기 기상예보를 위해 관측된 자료를 해석하며, 기상도를 작성합니다.'},
   {'work': '기상관측 기기의 정밀도를 향상시키고자 기상계측 기술개발에 대한 연구를 수행합니다.'},
   {'work': '정확한 기상정보를 제공하기 위해 기후예측시스템을 구축합니다.'}],
  'interestList': [{'interest': '기상관측자료를 분석하고 해석하는 것에 관심이 있고, 깊게 탐구하는 과정을 즐기는 사람에게 적합합니다.'},
   {'interest': '대기, 기후, 기상 등 기상 자료에 관심이 있고, 기계를 조작하는 활동을 좋아하는 사람에게 적합합니다.'}],
  'researchList': [{'research': '기후변화체험관 방문 - 기후변화체험관에 방문하여 세계의 기후변화와 환경문제에 대한 전시를 관람해볼 수 있습니다.'},
   {'research': '환경보호 공모전 참여 - 환경보호를 주제로 한 다양한 포스터, 사진 공모전 등이 개최됩니다. 대기환경을 주제로 하여 공모전에 참여해보고 환경보호의 중요성을 상기할 수 있습니다.'}],
  'baseInfo': {'aptit_name': '이학 전문직',
   'INTRST_JOB_YN': 'N',
   'emp_job_nm': '자연과학 연구원',
   'social': '매우좋음',
   'emp_job_cd': '1211',
   'job_cd': 6,
   'satisfication': 70.9,
   'rel_job_nm': '기상학연구원',
   'job_nm': '기상연구원',
   'std_job_nm': '자연과학 연구원',
   'wlb': '좋음',
   'std_job_cd': '2112',
   'wage_source': '기상연구원의 관련 직업인 천문·기상학연구원의 평균연봉(중앙값)은 4,662만원으로, 조사 대상 전체 직업 평균연봉(중앙값)인 4,072만원과 비교하여 높은 수준입니다. (자료 : 워크넷, 천문·기상학연구원(2021))',
   'edit_dt': '2025-06-04',
   'reg_dt': '2023-02-22',
   'satisfi_source': '기상연구원의 관련 직업인 천문·기상학연구원의 일자리 증가 가능성, 발전가능성 및 고용안정에 대해 재직자가 느끼는 직업만족도는 70.9%입니다. (자료: 워크넷, 천문·기상학연구원(2021))',
   'tag': '기상예보, 기상관측',
   'seq': 8,
   'views': 188811,
   'likes': 90,
   'wage': '4,662'},
  'jobReadyList': {'recruit': [{'recruit': '공개 채용이나 특별 채용을 통해 국립천문대, 기상대, 기상청, 기상연구소 등에 취업할 수 있습니다.'}],
   'certificate': [{'certificate': '특별히 요구되는 국가자격증이나 민간자격증은 없습니다. 다만, 국가자격증으로는 한국산업인력공단에서 시행하는 기상기사, 기상예보기술사, 기상감정기사 자격증이 있습니다.'}],
   'training': [],
   'curriculum': [{'curriculum': '대학교, 대학원에서 대기과학과, 천문학과 등 대기학 관련 학과를 졸업하면 유리합니다.'}]},
  'forecastList': [{'forecast': '향후 5년간 기상연구원의 관련 직업인 천문·기상학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 기초과학 분야의 연구 사업은 정부의 정책적 지원에 큰 영향을 받는데, 특히 정부가 국가경쟁력의 핵심 요소가 되는 과학기술 인력의 체계적 육성과 지원을 중요한 정책적 과제로 삼고 있고, 이에 수반되는 예산을 대폭 늘릴 예정이므로 향후 자연과학 관련 인력의 수요가 증가할 것으로 판단됩니다. 따라서 향후 천문 및 기상학연구원의 일자리도 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  'eduChart': [{'chart_name': '중졸이하,고졸,전문대졸,대졸,대학원졸,박사졸',
    'chart_data': '0,0,0,23,50,27',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
  'performList': {'environment': [],
   'perform': [{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
     'importance': 99,
     'perform': '문제 해결',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '다양한 목적을 위해 소프트웨어나 인터넷을 활용하거나 프로그램을 작성한다',
     'importance': 98,
     'perform': '전산',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '자신의 위치를 파악하거나 다른 대상들이 자신을 중심으로 어디에 있는지 안다',
     'importance': 98,
     'perform': '공간지각력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
     'importance': 96,
     'perform': '수리력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '먼 곳이나 가까운 것을 보기 위해 눈을 사용한다',
     'importance': 96,
     'perform': '시력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
     'importance': 95,
     'perform': '범주화',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '새로운 것을 배우거나 가르칠 때 적절한 방법을 활용한다',
     'importance': 95,
     'perform': '학습전략',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '문제를 해결하기 위해(혹은 의사결정을 하기 위해) 체계적으로 이치에 맞는 생각을 해낸다',
     'importance': 94,
     'perform': '논리적 분석',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '이득과 손실을 평가해서 결정을 내린다',
     'importance': 93,
     'perform': '판단과 의사결정',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
    {'inform': '문제해결 및 의사결정을 위해 새로운 정보가 가지는 의미를 파악한다',
     'importance': 93,
     'perform': '추리력',
     'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
   'knowledge': []},
  'majorChart': [{'major': '인문계열,사회계열,교육계열,공학계열,자연계열,의학계열,예체능계열',
    'major_data': '0,0,0,27,73,0,0',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}],
  'abilityList': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  'departList': [{'depart_id': 111, 'depart_name': '대기과학과'},
   {'depart_id': 541, 'depart_name': '천문학과'}],
  'relSolList': [],
  'tagList': ['기상예보', ' 기상관측'],
  'certiList': [{'certi': '기상기사'}, {'certi': '기상예보기술사'}, {'certi': '기상감정기사'}],
  'relVideoList': [{'video_name': '2020년 해양직업의 세계 - 꿈꾸는 장보고',
    'THUMBNAIL_FILE_SER': 52807,
    'job_cd': 6,
    'OUTPATH3': 'https://cdn.career.go.kr/cnet/real/upload/2021/03/29/20210329010713256_0.mp4',
    'video_id': 1034449,
    'CID': 36063},
   {'video_name': '산악기상컨설턴트(간추린영상)',
    'THUMBNAIL_FILE_SER': 38073,
    'job_cd': 6,
    'THUMNAIL_PATH': '2015/10/00000049870080049051_01.jpg',
    'OUTPATH3': 'https://cdn.career.go.kr/cnet/real/upload/2015/10/00000049870080049051.mp4',
    'video_id': 1012037,
    'CID': 12928},
   {'video_name': '화산지진전문가, 산악기상컨설턴트-일본에서 ‘화산·지진연구가’를 만나다',
    'THUMBNAIL_FILE_SER': 38057,
    'job_cd': 6,
    'THUMNAIL_PATH': '2015/09/00000049628160052290_01.jpg',
    'OUTPATH3': 'https://cdn.career.go.kr/cnet/real/upload/2015/09/00000049628160052290.mp4',
    'video_id': 1011228,
    'CID': 12116},
   {'video_name': '기상연구원',
    'THUMBNAIL_FILE_SER': 38222,
    'job_cd': 6,
    'THUMNAIL_PATH': '2013/03/00000041662080064963_01.jpg',
    'OUTPATH3': 'https://cdn.career.go.kr/cnet/real/upload/2013/03/00000041662080064963.mp4',
    'video_id': 1000730,
    'CID': 1474}],
  'aptitudeList': [{'aptitude': '기상 관측 자료를 분석하여 일기예보를 하기 위해서 논리적으로 사고하여 문제를 해결할 수 있는 수리·논리력이 필요합니다.'}],
  'jobRelOrgList': [{'rel_org': '기상청 날씨누리',
    'rel_org_url': 'https://www.weather.go.kr'},
   {'rel_org': '국립기상과학원', 'rel_org_url': 'http://www.nims.go.kr'}],
  'relJinsolList': [],
  'indicatorChart': [{'indicator': '융합성,대인관계,창의성,일가정균형,소득수준,고용유지,사회공헌',
    'indicator_data': '97.2,43.1,87.7,65.5,86.5,76.8,92.2',
    'source': '[자료 : 한국직업능력연구원, 맞춤형취업지원을 위한 직업지표 연구(2020-22)]'}]},
 {'workList': [{'work': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
   {'work': '물질과 구조의 운동, 전기나 빛 등 에너지의 발생과 이동, 물질과 에너지의 상호 관계에 대한 연구와 실험을 합니다.'},
   {'work': '물질과 에너지의 관계 등 물리학적 현상에 대해 관찰, 실험합니다.'},
   {'work': '고형 물질의 구조와 특성을 조사하기 위해 온도, 압력 등의 환경조건을 변화시켜 실험하고 반응을 연구합니다.'},
   {'work': '다양한 물리학적 기본 원리를 적용하여 재료, 전기, 자기, 광학, 의료, 음향, 빛 등 일상생활을 편리하게 하는 기구 개발에 대해 연구합니다.'}],
  'interestList': [{'interest': '자연현상에 대해 호기심을 가지고 관찰하는 것을 좋아하고, 깊게 탐구하는 과정을 즐기는 사람에게 적합합니다.'},
   {'interest': '문제에 대한 답을 구하기 위해 정보를 분석하는 것에 관심이 있고, 논리적이고 합리적인 사고를 하는 사람에게 적합합니다.'}],
  'researchList': [{'research': '물리학 진로체험 프로그램 참여 - 지역의 청소년수련관에서 주관하는 물리학 관련 진로체험 프로그램 참여를 통해 물리학 관련 직업에 대해 알아볼 수 있습니다.'},
   {'research': '국립과학관 관람 - 국립과천과학관 등 과학관 방문을 통해 과학 관련 전시를 관람하며 기초적인 물리 이론을 탐색할 수 있습니다.'}],
  'baseInfo': {'aptit_name': '이학 전문직',
   'INTRST_JOB_YN': 'N',
   'emp_job_nm': '자연과학 연구원',
   'social': '매우좋음',
   'emp_job_cd': '1211',
   'job_cd': 8,
   'satisfication': 79.8,
   'rel_job_nm': '광물리학자, 물리학자, 핵물리학자',
   'job_nm': '물리학연구원',
   'std_job_nm': '자연과학 연구원',
   'wlb': '좋음',
   'std_job_cd': '2112',
   'wage_source': '물리학연구원의 평균연봉(중앙값)은 6,734만원으로, 조사 대상 전체 직업 평균연봉(중앙값)인 4,072만원과 비교하여 높은 수준입니다. (자료 : 워크넷, 물리학연구원(2021))',
   'edit_dt': '2023-02-22',
   'reg_dt': '2023-02-22',
   'satisfi_source': '물리학연구원의 일자리 증가 가능성, 발전가능성 및 고용안정에 대해 재직자가 느끼는 직업만족도는 79.8%입니다. (자료: 워크넷, 물리학연구원(2021))',
   'tag': '물리학, 자연현상',
   'seq': 11,
   'views': 267284,
   'likes': 298,
   'wage': '6,734'},
  'jobReadyList': {'recruit': [{'recruit': '공개 채용이나 특별 채용을 통해 정부출연연구소 등에 취업할 수 있습니다.'},
    {'recruit': '대학, 기업부설연구소, 과학 및 공학 컨설팅회사 등에 취업할 수 있습니다.'}],
   'certificate': [],
   'training': [],
   'curriculum': [{'curriculum': '대학교, 대학원에서 물리학과, 지구환경과학과 등 물리 관련 학과를 졸업하면 유리합니다.'}]},

In [ ]:
detail_ls = []

for d in all_details:
  detail_dict = {}

  detail_dict["직업코드"] = d["baseInfo"]["job_cd"]

  detail_dict["직업명"] = d["baseInfo"]["job_nm"]

  detail_dict["직업분류"] = d["baseInfo"]["aptit_name"]

  detail_dict["하는일"] = d["workList"]

  detail_dict["핵심능력"] = d["abilityList"]

  detail_dict["관련학과"] = d["departList"]

  detail_dict["적성"] = d["aptitudeList"]

  detail_dict["흥미"] = d["interestList"]

  detail_dict["직업전망"] = d["forecastList"]

  detail_dict["업무환경"] = d["performList"]["environment"]

  detail_dict["업무수행"] = d["performList"]["perform"]

  detail_ls.append(detail_dict)

detail_ls

[{'직업코드': 1,
  '직업명': '가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원',
  '직업분류': '안전 관련직',
  '하는일': [{'work': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가구나 업소에 방문해서 가스, 수도, 전력 사용량을 검침하고 기록하는 업무를 수행합니다.'},
   {'work': '가스, 수도, 전력 등의 사용량에 따라 검침 서류를 대단위, 소단위 소비자와 지역으로 구분하여 전산에 입력합니다.'},
   {'work': '계량기의 불량 상태 등을 점검하고, 계량기 표면의 이물질을 제거합니다.'}],
  '핵심능력': [{'SORT_ORDR': '01', 'ability_name': '신체·운동능력'}],
  '관련학과': [],
  '적성': [{'aptitude': '많은 가정을 돌아다니면서 검침 업무를 수행해야 하므로 원활한 의사소통을 하기 위한 대인관계능력이 필요합니다.'}],
  '흥미': [{'interest': '기계나 기구를 조작하는 것을 좋아하고, 직접 느끼고 움직이는 체험을 중시하는 사람에게 적합합니다.'},
   {'interest': '고객에 대한 서비스 정신에 관심이 많고, 맡은 일에 대한 책임감이 있는 사람에게 적합합니다.'}],
  '직업전망': [],
  '업무환경': [{'environment': '걷거나 뛰기',
    'inform': '걷거나 뛰면서 근무하는 빈도',
    'importance': 100,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '균형을 유지하기',
    'inform': '(몸의) 균형을 유지하면서 근무하는 빈도',
    'importance': 99,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '비좁은 업무 공간',
    'inform': '불편한 자세를 취해야 하는 비좁은 공간에 노출되는 빈도',
    'importance': 98,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '실외 근무',
    'inform': '바깥공기에 노출되는 실외에서 근무하는 빈도',
    'importance': 97,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '매우 춥거나 더운 기온',
    'inform': '매우 덥거나(섭씨 32도 이상) 매우 추운(섭씨 0도 이하) 기온에 노출되는 빈도',
    'importance': 93,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '불쾌하거나 무례한 사람 상대',
    'inform': '불쾌하거나, 화나거나, 혹은 무례한 사람을 대하는 빈도',
    'importance': 92,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '몸을 구부리거나 비틀기',
    'inform': '몸을 구부리거나 비틀면서 근무하는 빈도',
    'importance': 88,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '갈등 상황',
    'inform': '업무 수행 시 갈등 상황 노출 정도',
    'importance': 87,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '사물, 도구, 조종 장치를 다루기 위해 손사용',
    'inform': '손으로 사물, 도구 혹은 조종 장치를 다루면서 근무하는 빈도',
    'importance': 79,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'environment': '반복적인 신체행동, 정신적 활동',
    'inform': '지속적이고 반복적인 신체적 행동이나 정신적 활동의 중요성',
    'importance': 72,
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'}],
  '업무수행': [{'inform': '기계가 제대로 작동하는지 확인하기 위해 표시판이나 계기판 등을 살펴본다',
    'importance': 72,
    'perform': '작동 점검',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '오작동의 원인이 무엇인가를 확인하고 이를 어떻게 처리할 것인지 결정한다',
    'importance': 54,
    'perform': '고장의 발견·수리',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '장비 혹은 시스템을 조작하고 통제한다',
    'importance': 47,
    'perform': '조작 및 통제',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '자신의 시간과 다른 사람의 시간을 관리한다',
    'importance': 35,
    'perform': '시간 관리',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
    'importance': 33,
    'perform': '수리력',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '다른 사람들을 돕기 위해 적극적으로 노력한다',
    'importance': 30,
    'perform': '서비스 지향',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '품질 또는 성과를 평가하기 위하여 제품, 서비스, 공정을 검사하거나 조사한다',
    'importance': 29,
    'perform': '품질관리분석',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '업무를 수행하는데 필요한 도구나 장비를 결정한다',
    'importance': 29,
    'perform': '장비 선정',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
    'importance': 29,
    'perform': '문제 해결',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'},
   {'inform': '신체의 균형을 유지하거나 각 부위를 구부리고 편다',
    'importance': 28,
    'perform': '유연성 및 균형',
    'source': '[자료 : 워크넷, 계기검침원및가스점검원 직업정보(2021)]'}]},
 {'직업코드': 5,
  '직업명': '일기예보관',
  '직업분류': '이학 전문직',
  '하는일': [{'work': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표하는 업무를 수행합니다.'},
   {'work': '기류의 방향, 속도, 온도, 습도, 기압 등 지구 대기의 물리적 특성과 그 특성에 영향을 미치는 요인을 조사하여 일기도를 작성합니다.'},
   {'work': '기상 관측 자료의 분석을 통해 장기, 단기 일기예보와 기상현상에 대한 주의보, 경보, 기상 전망을 발표합니다.'}],
  '핵심능력': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  '관련학과': [{'depart_id': 111, 'depart_name': '대기과학과'},
   {'depart_id': 541, 'depart_name': '천문학과'}],
  '적성': [{'aptitude': '기상 관측 자료의 분석을 바탕으로 일기예보를 하기 위해서 논리적으로 사고하여 문제를 해결할 수 있는 수리·논리력이 필요합니다.'}],
  '흥미': [{'interest': '기상학, 수학, 물리학에 관심이 있고, 새로운 것에 대한 호기심을 가진 사람에게 적합합니다.'},
   {'interest': '기상 관측 자료를 분석하는 것에 관심이 있고, 세심하고 꼼꼼한 성격의 사람에게 적합합니다.'}],
  '직업전망': [{'forecast': '향후 5년간 일기예보관의 관련 직업인 천문·기상학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 기초과학 분야의 연구 사업은 정부의 정책적 지원에 큰 영향을 받는데, 특히 정부가 국가경쟁력의 핵심 요소가 되는 과학기술 인력의 체계적 육성과 지원을 중요한 정책적 과제로 삼고 있고, 이에 수반되는 예산을 대폭 늘릴 예정이므로 향후 자연과학 관련 인력의 수요가 증가할 것으로 판단됩니다. 따라서 향후 천문 및 기상학연구원의 일자리도 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  '업무환경': [],
  '업무수행': [{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
    'importance': 99,
    'perform': '문제 해결',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '다양한 목적을 위해 소프트웨어나 인터넷을 활용하거나 프로그램을 작성한다',
    'importance': 98,
    'perform': '전산',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '자신의 위치를 파악하거나 다른 대상들이 자신을 중심으로 어디에 있는지 안다',
    'importance': 98,
    'perform': '공간지각력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
    'importance': 96,
    'perform': '수리력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '먼 곳이나 가까운 것을 보기 위해 눈을 사용한다',
    'importance': 96,
    'perform': '시력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
    'importance': 95,
    'perform': '범주화',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '새로운 것을 배우거나 가르칠 때 적절한 방법을 활용한다',
    'importance': 95,
    'perform': '학습전략',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '문제를 해결하기 위해(혹은 의사결정을 하기 위해) 체계적으로 이치에 맞는 생각을 해낸다',
    'importance': 94,
    'perform': '논리적 분석',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '이득과 손실을 평가해서 결정을 내린다',
    'importance': 93,
    'perform': '판단과 의사결정',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '문제해결 및 의사결정을 위해 새로운 정보가 가지는 의미를 파악한다',
    'importance': 93,
    'perform': '추리력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}]},
 {'직업코드': 6,
  '직업명': '기상연구원',
  '직업분류': '이학 전문직',
  '하는일': [{'work': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를 할 수 있는 방법을 연구하고 개발합니다.'},
   {'work': '기류의 방향, 속도, 기압, 온도, 습도 등 기상현상과 대기, 기후, 해양기상, 지진 특성 등을 조사하고 분석하여 보다 정확한 일기예보 기법을 개발하기 위한 연구를 합니다.'},
   {'work': '대기 상황에 대한 자료를 분석하고, 장기, 단기 기상예보를 위해 관측된 자료를 해석하며, 기상도를 작성합니다.'},
   {'work': '기상관측 기기의 정밀도를 향상시키고자 기상계측 기술개발에 대한 연구를 수행합니다.'},
   {'work': '정확한 기상정보를 제공하기 위해 기후예측시스템을 구축합니다.'}],
  '핵심능력': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  '관련학과': [{'depart_id': 111, 'depart_name': '대기과학과'},
   {'depart_id': 541, 'depart_name': '천문학과'}],
  '적성': [{'aptitude': '기상 관측 자료를 분석하여 일기예보를 하기 위해서 논리적으로 사고하여 문제를 해결할 수 있는 수리·논리력이 필요합니다.'}],
  '흥미': [{'interest': '기상관측자료를 분석하고 해석하는 것에 관심이 있고, 깊게 탐구하는 과정을 즐기는 사람에게 적합합니다.'},
   {'interest': '대기, 기후, 기상 등 기상 자료에 관심이 있고, 기계를 조작하는 활동을 좋아하는 사람에게 적합합니다.'}],
  '직업전망': [{'forecast': '향후 5년간 기상연구원의 관련 직업인 천문·기상학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 기초과학 분야의 연구 사업은 정부의 정책적 지원에 큰 영향을 받는데, 특히 정부가 국가경쟁력의 핵심 요소가 되는 과학기술 인력의 체계적 육성과 지원을 중요한 정책적 과제로 삼고 있고, 이에 수반되는 예산을 대폭 늘릴 예정이므로 향후 자연과학 관련 인력의 수요가 증가할 것으로 판단됩니다. 따라서 향후 천문 및 기상학연구원의 일자리도 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  '업무환경': [],
  '업무수행': [{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다',
    'importance': 99,
    'perform': '문제 해결',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '다양한 목적을 위해 소프트웨어나 인터넷을 활용하거나 프로그램을 작성한다',
    'importance': 98,
    'perform': '전산',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '자신의 위치를 파악하거나 다른 대상들이 자신을 중심으로 어디에 있는지 안다',
    'importance': 98,
    'perform': '공간지각력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
    'importance': 96,
    'perform': '수리력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '먼 곳이나 가까운 것을 보기 위해 눈을 사용한다',
    'importance': 96,
    'perform': '시력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
    'importance': 95,
    'perform': '범주화',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '새로운 것을 배우거나 가르칠 때 적절한 방법을 활용한다',
    'importance': 95,
    'perform': '학습전략',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '문제를 해결하기 위해(혹은 의사결정을 하기 위해) 체계적으로 이치에 맞는 생각을 해낸다',
    'importance': 94,
    'perform': '논리적 분석',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '이득과 손실을 평가해서 결정을 내린다',
    'importance': 93,
    'perform': '판단과 의사결정',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'},
   {'inform': '문제해결 및 의사결정을 위해 새로운 정보가 가지는 의미를 파악한다',
    'importance': 93,
    'perform': '추리력',
    'source': '[자료 : 워크넷, 천문·기상학연구원 직업정보(2021)]'}]},
 {'직업코드': 8,
  '직업명': '물리학연구원',
  '직업분류': '이학 전문직',
  '하는일': [{'work': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명, 예측하고, 물리학적 원리와 기법을 산업, 의료, 군사 분야 등에 응용하기 위한 연구를 수행합니다.'},
   {'work': '물질과 구조의 운동, 전기나 빛 등 에너지의 발생과 이동, 물질과 에너지의 상호 관계에 대한 연구와 실험을 합니다.'},
   {'work': '물질과 에너지의 관계 등 물리학적 현상에 대해 관찰, 실험합니다.'},
   {'work': '고형 물질의 구조와 특성을 조사하기 위해 온도, 압력 등의 환경조건을 변화시켜 실험하고 반응을 연구합니다.'},
   {'work': '다양한 물리학적 기본 원리를 적용하여 재료, 전기, 자기, 광학, 의료, 음향, 빛 등 일상생활을 편리하게 하는 기구 개발에 대해 연구합니다.'}],
  '핵심능력': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  '관련학과': [{'depart_id': 177, 'depart_name': '물리학과'},
   {'depart_id': 523, 'depart_name': '지구환경과학과'}],
  '적성': [{'aptitude': '수학, 물리, 화학과 같은 자연과학에 대한 이해를 바탕으로 논리적으로 사고하여 문제를 해결하는 수리·논리력이 필요합니다.'}],
  '흥미': [{'interest': '자연현상에 대해 호기심을 가지고 관찰하는 것을 좋아하고, 깊게 탐구하는 과정을 즐기는 사람에게 적합합니다.'},
   {'interest': '문제에 대한 답을 구하기 위해 정보를 분석하는 것에 관심이 있고, 논리적이고 합리적인 사고를 하는 사람에게 적합합니다.'}],
  '직업전망': [{'forecast': '향후 5년간 물리학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 정부가 국가경쟁력의 핵심 요소가 되는 과학기술 인력의 체계적 육성과 지원을 중요한 정책적 과제로 제시하고 있고, 이에 수반되는 예산을 증액할 예정이므로 향후 자연과학 관련 인력의 수요가 증가할 것으로 판단됩니다. 이러한 상황을 종합하면 향후 물리학 연구원의 일자리는 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  '업무환경': [{'environment': '자동화 정도',
    'inform': '업무의 자동화 정도',
    'importance': 84,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '이메일 이용하기',
    'inform': '업무 수행하면서 이메일 사용하는 정도',
    'importance': 81,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '앉아서 근무',
    'inform': '앉아서 근무하는 빈도',
    'importance': 80,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '정확성, 정밀성 유지',
    'inform': '업무 수행을 위해 정밀하거나 정확한 것의 중요성',
    'importance': 78,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '반복적인 신체행동, 정신적 활동',
    'inform': '지속적이고 반복적인 신체적 행동이나 정신적 활동의 중요성',
    'importance': 72,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '균형을 유지하기',
    'inform': '(몸의) 균형을 유지하면서 근무하는 빈도',
    'importance': 64,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '실내 근무',
    'inform': '실내에서 근무하는 빈도',
    'importance': 64,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '연설, 발표, 회의하기',
    'inform': '사람들 앞에서 공식적으로 연설(발표,회의 등의 상황)',
    'importance': 63,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '공문, 문서 주고받기',
    'inform': '업무 수행하면서 공문이나 문서를 주고받는 정도',
    'importance': 62,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'environment': '재택근무',
    'inform': '재택근무 가능성',
    'importance': 60,
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'}],
  '업무수행': [{'inform': '어떤 문제를 해결하기 위해 수학을 사용한다',
    'importance': 98,
    'perform': '수리력',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
    'importance': 97,
    'perform': '범주화',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '글을 통해서 다른 사람과 효과적으로 의사소통한다',
    'importance': 95,
    'perform': '글쓰기',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '다른 사람들이 말하는 것을 집중해서 듣고 상대방이 말하려는 요점을 이해하거나 적절한 질문을 한다',
    'importance': 92,
    'perform': '듣고 이해하기',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '업무와 관련된 문서를 읽고 이해한다',
    'importance': 91,
    'perform': '읽고 이해하기',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '문제를 해결하기 위해(혹은 의사결정을 하기 위해) 체계적으로 이치에 맞는 생각을 해낸다',
    'importance': 89,
    'perform': '논리적 분석',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '자신의 위치를 파악하거나 다른 대상들이 자신을 중심으로 어디에 있는지 안다',
    'importance': 89,
    'perform': '공간지각력',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '주의를 산만하게 하는 자극에도 불구하고 원하는 일에 집중한다',
    'importance': 85,
    'perform': '선택적 집중력',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '주어진 주제나 상황에 대하여 독특하고 기발한 아이디어를 산출한다',
    'importance': 84,
    'perform': '창의력',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'},
   {'inform': '새로운 방법을 고안하고 기존의 방법을 개선하기 위해서 현재 사용되는 도구와 기술을 분석한다',
    'importance': 82,
    'perform': '기술 분석',
    'source': '[자료 : 워크넷, 물리학연구원 직업정보(2021)]'}]},
 {'직업코드': 10,
  '직업명': '방사선사',
  '직업분류': '의료관련 전문직',
  '하는일': [{'work': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 각종 방사선 장비를 조작하고, 방사성물질을 이용하여 치료하는 업무를 수행합니다.'},
   {'work': '신체 특정 부위에 대한 치료를 위해 X선(X-ray) 검사, 전산화단층촬영(CT : Computed Tomography) 검사, 자기공명영상촬영(MRI : Magnetic Resonance Imaging), 초음파 검사 등을 통해 환자의 상태를 정밀하게 진단합니다.'},
   {'work': '방사선 촬영과 치료를 위해 환자를 고정시키고, 의사의 지도에 따라 검사받지 않는 다른 신체 부위가 방사선에 노출되지 않도록 방사선 노출 범위와 강도를 조절하여 치료합니다.'},
   {'work': '방사선 촬영 결과를 정리, 분석하여 보고서를 작성하고, 의사에게 전달하며, 치료 기록을 관리합니다.'}],
  '핵심능력': [{'SORT_ORDR': '08', 'ability_name': '자기성찰능력'},
   {'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  '관련학과': [{'depart_id': 196, 'depart_name': '방사선과'}],
  '적성': [{'aptitude': '기계를 조작하여 환자의 상태를 진단, 치료하기 위해서 논리적으로 사고하여 문제를 해결할 수 있는 수리·논리력이 필요합니다.'},
   {'aptitude': '방사선 촬영, 결과물 분석, 보고서 작성, 치료 기록 관리 등 업무를 수행하기 위해 자신에게 주어진 여러 자원을 관리하는 자기성찰능력이 필요합니다.'}],
  '흥미': [{'interest': '의료장비를 다루는 것에 관심이 있고, 직접 기계를 조작하여 사용하는 것을 즐기는 사람에게 적합합니다.'},
   {'interest': '자료를 분석하여 보고서를 작성하는 업무에 관심이 있고, 논리적이고 합리적인 사고 과정을 즐기는 사람에게 적합합니다.'}],
  '직업전망': [{'forecast': '향후 5년간 방사선사의 일자리 규모는 다소 증가할 것으로 전망됩니다. 의료기기의 첨단화, 자동화가 진행되고 있으나 개인이 가진 특성이 다르므로 방사선 검사는 개별적인 검사가 요구되고, 검사의 기계화와 자동화에도 불구하고 전문가의 손길이 필요한 영역이므로 방사선사에 대한 수요는 지속적으로 발생할 것으로 보입니다. 이러한 상황을 종합하면 향후 방사선사의 일자리는 다소 증가할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  '업무환경': [{'environment': '질병 혹은 감염 위험 노출',
    'inform': '질병 혹은 병균에 노출되는 빈도',
    'importance': 100,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '위험한 상태 노출',
    'inform': '위험한 상태(고압 전류, 가연성 물질, 폭발물, 화학물 등)에 노출되는 빈도',
    'importance': 96,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '사물, 도구, 조종 장치를 다루기 위해 손사용',
    'inform': '손으로 사물, 도구 혹은 조종 장치를 다루면서 근무하는 빈도',
    'importance': 89,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '자동화 정도',
    'inform': '업무의 자동화 정도',
    'importance': 88,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '이미지/평판/재정에 미치는 영향력',
    'inform': '본인의 의사결정이 다른 사람 또는 회사 이미지/평판/재정에 영향을 주는 빈도',
    'importance': 87,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '실수의 심각성',
    'inform': '실수 결과의 심각성',
    'importance': 86,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '정확성, 정밀성 유지',
    'inform': '업무 수행을 위해 정밀하거나 정확한 것의 중요성',
    'importance': 84,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '다른 사람과의 접촉',
    'inform': '업무 수행하면서 사람들과 접촉(전화, 대면, 메신저 등) 정도',
    'importance': 81,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '반복적인 신체행동, 정신적 활동',
    'inform': '지속적이고 반복적인 신체적 행동이나 정신적 활동의 중요성',
    'importance': 80,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'environment': '보호장비 착용',
    'inform': '업무 수행 시 보호장비(안전화, 보안경, 장갑, 귀마개, 안전모, 구명조끼, 전신보호복 등) 착용 정도',
    'importance': 77,
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'}],
  '업무수행': [{'inform': '장비 혹은 시스템을 조작하고 통제한다',
    'importance': 90,
    'perform': '조작 및 통제',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '기계가 제대로 작동하는지 확인하기 위해 표시판이나 계기판 등을 살펴본다',
    'importance': 88,
    'perform': '작동 점검',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '장비에 대한 일상적인 유지보수를 하고 장비를 유지하기 위해 언제 어떤 종류의 조치를 취해야 하는가를 안다',
    'importance': 72,
    'perform': '장비의 유지',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '다른 사람들을 돕기 위해 적극적으로 노력한다',
    'importance': 70,
    'perform': '서비스 지향',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '신체를 사용하여 기계나 기구를 정확한 위치로 빠르게 움직인다',
    'importance': 69,
    'perform': '움직임 통제',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '신체의 균형을 유지하거나 각 부위를 구부리고 편다',
    'importance': 65,
    'perform': '유연성 및 균형',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '오작동의 원인이 무엇인가를 확인하고 이를 어떻게 처리할 것인지 결정한다',
    'importance': 64,
    'perform': '고장의 발견·수리',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '신호에 빠르게 반응하거나 신체를 신속히 움직인다',
    'importance': 60,
    'perform': '반응시간과 속도',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '업무와 관련된 문서를 읽고 이해한다',
    'importance': 56,
    'perform': '읽고 이해하기',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'},
   {'inform': '업무를 수행하는데 필요한 도구나 장비를 결정한다',
    'importance': 52,
    'perform': '장비 선정',
    'source': '[자료 : 워크넷, 방사선사 직업정보(2021)]'}]},
 {'직업코드': 13,
  '직업명': '생물학연구원',
  '직업분류': '이학 전문직',
  '하는일': [{'work': '생물학연구원은 생명체에 대한 기원, 발달, 구조, 해부, 환경 등에 대해 연구하고, 연구 결과를 의학, 농업 등 다른 분야에 적용하거나 응용하는 방법을 연구, 개발합니다.'},
   {'work': '생명체의 기원, 발달, 구조, 환경, 기타 생활방식 등에 대한 현지 조사와 실험실 연구를 수행합니다.'},
   {'work': '과학 장비들을 사용하여 실험실에서 생물 표본을 연구하고 실험합니다.'},
   {'work': '통계학적 기술을 이용해서 자료를 분석하고 평가합니다.'},
   {'work': '의학, 농업, 약품 제조 등의 분야에 활용하기 위한 보고서를 작성하는 등 심화 연구를 수행합니다.'}],
  '핵심능력': [{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}],
  '관련학과': [{'depart_id': 265, 'depart_name': '생물학과'}],
  '적성': [{'aptitude': '자연법칙과 과학적 연구 방법에 대해 논리적으로 사고하여 문제를 해결하는 수리·논리력이 필요합니다.'}],
  '흥미': [{'interest': '장시간의 실험과 분석을 수행해야 하므로 깊게 탐구하는 과정을 즐기고, 새로운 것에 대해 호기심을 가진 사람에게 적합합니다.'},
   {'interest': '생명체와 생명현상을 직접 느끼는 것을 좋아하고, 체험을 중시하는 사람에게 적합합니다.'}],
  '직업전망': [{'forecast': '향후 5년간 생물학연구원의 일자리 규모는 다소 증가할 것으로 전망됩니다. 미래 국가경쟁력을 높이고 발전의 중심이 될 바이오 제약, 바이오에너지, 뇌과학 등 첨단 생명공학 기술개발과 바이오산업 육성에 국가적 차원의 노력을 기울이고 있으므로, 생명공학산업의 기반이 되는 각종 기초연구와 응용연구를 수행하는 생명과학연구원의 일자리도 증가할 것으로 예상됩니다. 특히 줄기세포 연구, 뇌 연구, 신약 개발 관련한 인력이 집중적으로 필요할 것으로 예측되고 있습니다. (자료: 워크넷 직업정보)'}],
  '업무환경': [{'environment': '이메일 이용하기',
    'inform': '업무 수행하면서 이메일 사용하는 정도',
    'importance': 91,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '공문, 문서 주고받기',
    'inform': '업무 수행하면서 공문이나 문서를 주고받는 정도',
    'importance': 86,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '앉아서 근무',
    'inform': '앉아서 근무하는 빈도',
    'importance': 85,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '정확성, 정밀성 유지',
    'inform': '업무 수행을 위해 정밀하거나 정확한 것의 중요성',
    'importance': 82,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '질병 혹은 감염 위험 노출',
    'inform': '질병 혹은 병균에 노출되는 빈도',
    'importance': 82,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '균형을 유지하기',
    'inform': '(몸의) 균형을 유지하면서 근무하는 빈도',
    'importance': 82,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '전화 대화하기',
    'inform': '업무 수행하면서 전화로 대화하는 정도',
    'importance': 80,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '위험한 상태 노출',
    'inform': '위험한 상태(고압 전류, 가연성 물질, 폭발물, 화학물 등)에 노출되는 빈도',
    'importance': 74,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '치열한 경쟁',
    'inform': '동료 혹은 다른 사람들과의 경쟁 정도',
    'importance': 72,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'environment': '다른 사람과의 접촉',
    'inform': '업무 수행하면서 사람들과 접촉(전화, 대면, 메신저 등) 정도',
    'importance': 72,
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'}],
  '업무수행': [{'inform': '업무를 완료하기 위해 필요한 비용을 파악하고 구체적 소요 내역을 산출한다',
    'importance': 100,
    'perform': '재정 관리',
    'source': '[자료 : 워크넷, 생물학연구원 직업정보(2021)]'},
   {'inform': '기준이나 법칙을 정하고 그에 따라 사물이나 행위를 분류한다',
    'importance': 100,
    'perform': '범주화',

In [ ]:
table = pd.DataFrame.from_dict(detail_ls, orient = "columns")
table

,직업코드,직업명,직업분류,하는일,핵심능력,관련학과,적성,흥미,직업전망,업무환경,업무수행
0,1,가스ㆍ수도ㆍ전기 계기 검침원 및 안전점검원,안전 관련직,[{'work': '가스·수도·전기 계기 검침원 및 안전점검원은 정기적으로 담당 가...,"[{'SORT_ORDR': '01', 'ability_name': '신체·운동능력'}]",[],[{'aptitude': '많은 가정을 돌아다니면서 검침 업무를 수행해야 하므로 원...,"[{'interest': '기계나 기구를 조작하는 것을 좋아하고, 직접 느끼고 움직...",[],"[{'environment': '걷거나 뛰기', 'inform': '걷거나 뛰면서 ...",[{'inform': '기계가 제대로 작동하는지 확인하기 위해 표시판이나 계기판 등...
1,5,일기예보관,이학 전문직,[{'work': '일기예보관은 각종 기상 관측 자료의 분석을 바탕으로 일기예보와 ...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}]","[{'depart_id': 111, 'depart_name': '대기과학과'}, {...",[{'aptitude': '기상 관측 자료의 분석을 바탕으로 일기예보를 하기 위해서...,"[{'interest': '기상학, 수학, 물리학에 관심이 있고, 새로운 것에 대한...",[{'forecast': '향후 5년간 일기예보관의 관련 직업인 천문·기상학연구원의...,[],"[{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다', ..."
2,6,기상연구원,이학 전문직,[{'work': '기상연구원은 각종 기상 관측 자료를 분석하여 정확하게 일기예보를...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}]","[{'depart_id': 111, 'depart_name': '대기과학과'}, {...",[{'aptitude': '기상 관측 자료를 분석하여 일기예보를 하기 위해서 논리적...,"[{'interest': '기상관측자료를 분석하고 해석하는 것에 관심이 있고, 깊게...",[{'forecast': '향후 5년간 기상연구원의 관련 직업인 천문·기상학연구원의...,[],"[{'inform': '문제의 본질을 파악하여 해결 방법을 찾고 이를 실행한다', ..."
3,8,물리학연구원,이학 전문직,"[{'work': '물리학연구원은 자연현상의 기본 법칙을 규명하여 합리적으로 설명,...","[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}]","[{'depart_id': 177, 'depart_name': '물리학과'}, {'...","[{'aptitude': '수학, 물리, 화학과 같은 자연과학에 대한 이해를 바탕으...","[{'interest': '자연현상에 대해 호기심을 가지고 관찰하는 것을 좋아하고,...",[{'forecast': '향후 5년간 물리학연구원의 일자리 규모는 다소 증가할 것...,"[{'environment': '자동화 정도', 'inform': '업무의 자동화 ...","[{'inform': '어떤 문제를 해결하기 위해 수학을 사용한다', 'import..."
4,10,방사선사,의료관련 전문직,"[{'work': '방사선사는 의사를 보조하여 신체의 질병, 장애를 진단하기 위해 ...","[{'SORT_ORDR': '08', 'ability_name': '자기성찰능력'}...","[{'depart_id': 196, 'depart_name': '방사선과'}]","[{'aptitude': '기계를 조작하여 환자의 상태를 진단, 치료하기 위해서 논...","[{'interest': '의료장비를 다루는 것에 관심이 있고, 직접 기계를 조작하...",[{'forecast': '향후 5년간 방사선사의 일자리 규모는 다소 증가할 것으로...,"[{'environment': '질병 혹은 감염 위험 노출', 'inform': '...","[{'inform': '장비 혹은 시스템을 조작하고 통제한다', 'importanc..."
...,...,...,...,...,...,...,...,...,...,...,...
541,10108,배터리 기술자,공학 전문직,[{'work': '배터리 기술자는 2차 전지의 기본 단위가 되는 배터리 셀을 비롯...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}...","[{'depart_id': 86, 'depart_name': '기계공학과'}, {'...","[{'aptitude': '주어진 문제의 규칙을 발견하고, 논리적으로 사고하여 문제...",[{'interest': '논리적이고 합리적으로 생각하고 깊게 탐구하는 과정을 즐기...,[{'forecast': '앞으로 배터리 기술자의 일자리를 크게 증가할 것으로 전망...,"[{'environment': '위험한 상태 노출', 'inform': '위험한 상...",[{'inform': '새로운 방법을 고안하고 기존의 방법을 개선하기 위해서 현재 ...
542,10109,나노공학 기술자,공학 전문직,[{'work': '나노공학 기술자는 나노미터(1 나노는 10억 분의 1m)를 탐구...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}...","[{'depart_id': 456, 'depart_name': '재료공학과'}, {...",[{'aptitude': '수학 책에 나오는 용어나 기호를 잘 이해하고 논리적으로 ...,[{'interest': '새로운 것에 호기심이 많고 혼자서 하는 일에 집중하는 것...,[{'forecast': '앞으로 나노공학 기술자의 일자리는 증가할 것으로 전망됩니...,"[{'environment': '극단적으로 밝거나 부적절한 조명', 'inform'...",[{'inform': '새로운 방법을 고안하고 기존의 방법을 개선하기 위해서 현재 ...
543,10110,양자 컴퓨팅 기술자,공학 전문직,[{'work': '양자 컴퓨팅 기술자는 양자 물리학의 지식을 이용해서 기존 컴퓨터...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}...","[{'depart_id': 469, 'depart_name': '전자공학과'}, {...",[{'aptitude': '통계 자료를 잘 이해하고 까다롭고 복잡한 계산을 잘할 수...,[{'interest': '논리적이고 합리적으로 생각하고 깊게 탐구하는 과정을 즐기...,[{'forecast': '양자컴퓨터 개발자의 일자리 앞으로 증가할 것으로 예상됩니...,"[{'environment': '이메일 이용하기', 'inform': '업무 수행하...","[{'inform': '사용자의 요구에 맞도록 장비와 기술을 개발하여 적용한다', ..."
544,10111,핀테크 전문가,공학 전문직,[{'work': '핀테크 전문가는 금융 서비스에 정보기술을 적용하기 위한 방안을 ...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}...","[{'depart_id': 23, 'depart_name': '경영학과'}, {'d...",[{'aptitude': '수학 책에 나오는 용어나 기호를 잘 이해하고 통계자료를 ...,[{'interest': '혼자서 하는 일에 집중하고 새로운 것에 호기심에 많은 사...,[{'forecast': '앞으로 핀테크 전문가의 일자리는 증가할 것으로 예상됩니다...,"[{'environment': '앉아서 근무', 'inform': '앉아서 근무하는...",[{'inform': '직원의 근로의욕을 높이고 능력을 개발하며 적재적소에 인재를 ...
545,10112,스마트공장 기술자,공학 전문직,[{'work': '스마트공장 기술자는 제품의 전 생산과정을 사물인터넷(IoT)과 ...,"[{'SORT_ORDR': '07', 'ability_name': '수리·논리력'}...","[{'depart_id': 463, 'depart_name': '전기전자공학과'},...",[{'aptitude': '논리적으로 사고하여 문제를 해결할 수 있는 능력을 갖추어...,[{'interest': '깊게 탐구하는 과정을 즐기고 새로운 것에 호기심이 많은 ...,[{'forecast': '스마트 공장 기술자의 일자리는 앞으로 크게 늘어날 것으로...,"[{'environment': '갈등 상황', 'inform': '업무 수행 시 갈...","[{'inform': '사용자의 요구에 맞도록 장비와 기술을 개발하여 적용한다', ..."

In [ ]:
path = "/content/커리어넷_최최종.csv"
table.to_csv(path, index = False, encoding = "utf-8-sig")

In [ ]:
from google.colab import files
files.download("/content/커리어넷_최최종.csv")